// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SurgicalClinic.DataAccessLayer.Context;

#nullable disable

namespace SurgicalClinic.DataAccessLayer.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260827105249_HastaTcNoEklendi")]
    partial class HastaTcNoEklendi
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.18")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("SurgicalClinic.Entities.Concrete.Brans", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Ad")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Branslar");
                });

            modelBuilder.Entity("SurgicalClinic.Entities.Concrete.Doktor", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Aciklama")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Ad")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("KullaniciId")
                        .HasColumnType("int");

                    b.Property<string>("Soyad")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Unvan")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("KullaniciId")
                        .IsUnique()
                        .HasFilter("[KullaniciId] IS NOT NULL");

                    b.ToTable("Doktorlar");
                });

            modelBuilder.Entity("SurgicalClinic.Entities.Concrete.DoktorBrans", b =>
                {
                    b.Property<int>("DoktorId")
                        .HasColumnType("int");

                    b.Property<int>("BransId")
                        .HasColumnType("int");

                    b.HasKey("DoktorId", "BransId");

                    b.HasIndex("BransId");

                    b.ToTable("DoktorBranslar");
                });

            modelBuilder.Entity("SurgicalClinic.Entities.Concrete.Hasta", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Ad")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("DogumTarihi")
                        .HasColumnType("datetime2");

                    b.Property<string>("Notlar")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Soyad")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TcNo")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Telefon")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Hastalar");
                });

            modelBuilder.Entity("SurgicalClinic.Entities.Concrete.Islem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Aciklama")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Ad")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("BransId")
                        .HasColumnType("int");

                    b.Property<decimal>("Fiyat")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("FiyatTipi")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("BransId");

                    b.ToTable("Islemler");
                });

            modelBuilder.Entity("SurgicalClinic.Entities.Concrete.IslemSecenek", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<decimal>("Fiyat")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("IslemId")
                        .HasColumnType("int");

                    b.Property<string>("SecenekAd")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("IslemId");

                    b.ToTable("IslemSecenekler");
                });

            modelBuilder.Entity("SurgicalClinic.Entities.Concrete.Kullanici", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Ad")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Rol")
                        .HasColumnType("int");

                    b.Property<string>("Soyad")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("passwordHash")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Kullanicilar");
                });

            modelBuilder.Entity("SurgicalClinic.Entities.Concrete.Randevu", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("DoktorId")
                        .HasColumnType("int");

                    b.Property<string>("DoktorNotu")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Durum")
                        .HasColumnType("int");

                    b.Property<int>("HastaId")
                        .HasColumnType("int");

                    b.Property<string>("HastaNotu")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("IslemId")
                        .HasColumnType("int");

                    b.Property<int?>("IslemSecenekId")
                        .HasColumnType("int");

                    b.Property<int>("Kaynak")
                        .HasColumnType("int");

                    b.Property<DateTime>("OlusturmaTarihi")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("OnayTarihi")
                        .HasColumnType("datetime2");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.Property<TimeSpan>("Saat")
                        .HasColumnType("time");

                    b.Property<DateTime>("Tarih")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("DoktorId");

                    b.HasIndex("HastaId");

                    b.HasIndex("IslemId");

                    b.HasIndex("IslemSecenekId");

                    b.ToTable("Randevular");
                });

            modelBuilder.Entity("SurgicalClinic.Entities.Concrete.Doktor", b =>
                {
                    b.HasOne("SurgicalClinic.Entities.Concrete.Kullanici", "Kullanici")
                        .WithOne("Doktor")
                        .HasForeignKey("SurgicalClinic.Entities.Concrete.Doktor", "KullaniciId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Kullanici");
                });

            modelBuilder.Entity("SurgicalClinic.Entities.Concrete.DoktorBrans", b =>
                {
                    b.HasOne("SurgicalClinic.Entities.Concrete.Brans", "Brans")
                        .WithMany("DoktorBranslar")
                        .HasForeignKey("BransId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SurgicalClinic.Entities.Concrete.Doktor", "Doktor")
                        .WithMany("DoktorBranslar")
                        .HasForeignKey("DoktorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Brans");

                    b.Navigation("Doktor");
                });

            modelBuilder.Entity("SurgicalClinic.Entities.Concrete.Islem", b =>
                {
                    b.HasOne("SurgicalClinic.Entities.Concrete.Brans", "Brans")
                        .WithMany()
                        .HasForeignKey("BransId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Brans");
                });

            modelBuilder.Entity("SurgicalClinic.Entities.Concrete.IslemSecenek", b =>
                {
                    b.HasOne("SurgicalClinic.Entities.Concrete.Islem", "Islem")
                        .WithMany("Secenekler")
                        .HasForeignKey("IslemId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Islem");
                });

            modelBuilder.Entity("SurgicalClinic.Entities.Concrete.Randevu", b =>
                {
                    b.HasOne("SurgicalClinic.Entities.Concrete.Doktor", "Doktor")
                        .WithMany("Randevular")
                        .HasForeignKey("DoktorId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("SurgicalClinic.Entities.Concrete.Hasta", "Hasta")
                        .WithMany("Randevular")
                        .HasForeignKey("HastaId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("SurgicalClinic.Entities.Concrete.Islem", "Islem")
                        .WithMany("Randevular")
                        .HasForeignKey("IslemId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("SurgicalClinic.Entities.Concrete.IslemSecenek", "IslemSecenek")
                        .WithMany()
                        .HasForeignKey("IslemSecenekId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Doktor");

                    b.Navigation("Hasta");

                    b.Navigation("Islem");

                    b.Navigation("IslemSecenek");
                });

            modelBuilder.Entity("SurgicalClinic.Entities.Concrete.Brans", b =>
                {
                    b.Navigation("DoktorBranslar");
                });

            modelBuilder.Entity("SurgicalClinic.Entities.Concrete.Doktor", b =>
                {
                    b.Navigation("DoktorBranslar");

                    b.Navigation("Randevular");
                });

            modelBuilder.Entity("SurgicalClinic.Entities.Concrete.Hasta", b =>
                {
                    b.Navigation("Randevular");
                });

            modelBuilder.Entity("SurgicalClinic.Entities.Concrete.Islem", b =>
                {
                    b.Navigation("Randevular");

                    b.Navigation("Secenekler");
                });

            modelBuilder.Entity("SurgicalClinic.Entities.Concrete.Kullanici", b =>
                {
                    b.Navigation("Doktor");
                });
#pragma warning restore 612, 618
        }
    }
}
